# Generated by Django 3.2.3 on 2021-06-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airlineapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_in',
            old_name='airport_icao',
            new_name='airport',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='aircraft_id',
            new_name='aircraft',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='dispatcher_id',
            new_name='dispatcher',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='dpt_airport_icao',
            new_name='dpt_airport',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='dst_airport_icao',
            new_name='dst_airport',
        ),
    ]
