# Generated by Django 3.2.3 on 2021-06-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airlineapp', '0002_auto_20210601_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='dptTime',
            new_name='dpt_time',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='dstTime',
            new_name='dst_time',
        ),
    ]
